### ISSUE TITLE
NoSuchMethodError on creation of Tour object

### ISSUE THREAD

**Issue by PAX523** [Juchar/product-tour#8]
The plugin raises an exception immediately on creation of Tour object (``new Tour()``):

    Caused by: java.lang.NoSuchMethodError: org.vaadin.addons.producttour.tour.Tour.addListener(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/reflect/Method;)Lcom/vaadin/shared/Registration;
	at org.vaadin.addons.producttour.tour.Tour.addShowListener(Tour.java:81)
	at org.vaadin.addons.producttour.tour.Tour.<init>(Tour.java:69)
	at org.pevalidation.webapp.producttour.ProductTourGuide.startTutorial(ProductTourGuide.java:80)
        ...
     java.lang.NoClassDefFoundError: com/vaadin/shared/Registration
	at java.lang.Class.getDeclaredMethods0(Native Method)
     com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:101) 
      ...
     Caused by: java.lang.ClassNotFoundException: com.vaadin.shared.Registration
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)

I'm using ``product-tour:0.5``.

**Comment by PAX523** [comment]
It seems that it's not compatible with Vaadin 7.7.10

**Comment by PAX523** [comment]
Even ``org.vaadin.addons.producttour.button.StepButton`` expects a different method signature for registering the click listener:

    java.lang.NoSuchMethodError: org.vaadin.addons.producttour.button.StepButton.addListener(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/reflect/Method;)Lcom/vaadin/shared/Registration;
	at org.vaadin.addons.producttour.button.StepButton.addClickListener(StepButton.java:86)
	at org.vaadin.addons.producttour.button.StepButton.<init>(StepButton.java:73)
	at org.vaadin.addons.producttour.button.StepButton.<init>(StepButton.java:109)
	at pewebappenhanced.ProductTourTest.Instantiation and startin product tour works fine(ProductTourTest.groovy:32)

The method is contained by ``com.vaadin.server.AbstractClientConnector``. Its signature with ``vaadin-server-7.7.10`` looks like this:

    public void addListener(Class<?> eventType, Object target, Method method)

But expected is another signature which is available since ``vaadin-server-8.0.0``:

    public Registration addListener(Class<?> eventType, Object target, Method method)

**Comment by PAX523** [comment]
Obviously, only until ``product-tour:2.x`` is compatible with Vaadin 7.7.10. I recommend that you clarify this at your product page, explicitly. Otherwise, somebody simply takes the latest version and wonders why it doesn't work with Vaadin 7.
